@startuml
autonumber
actor "Client" as CLT

participant ":ViewTestsGUIScene" as UI1
participant ":ViewTestsGUISceneController" as CTRL
participant ":ViewTestDetailsGUIScene" as UI2
participant ":ViewTestDetailsGUISceneController" as CTRL2
participant ":Company" as CMP
participant "ts:\nTestStore" as TS
participant "t:\nTest" as T

activate CLT
CLT -> UI1 : view validated tests.
activate UI1
UI1 -> CTRL1 : loadData()
activate CTRL1
CTRL1 -> CMP : ts=getTestStore()
activate CMP
deactivate CMP
CTRL1 -> TS : lt=getValidatedTestsFromClient(CLT)
activate TS
deactivate TS
deactivate CTRL1
UI1 --> CLT : shows tests list and ask to select one
deactivate UI1

CLT -> UI1 : selects a test.
activate UI1
UI1 -> CTRL1 : showTest(t)
activate CTRL1
CTRL1 -> UI2 : loadViewTestDetailUi(t)
deactivate UI1
deactivate UI2
activate UI2
UI2 -> CTRL2 : loadData()
activate CTRL2
deactivate CTRL2
UI2 -> CLT : show test details.
deactivate UI2
deactivate CLT
@enduml