@startuml
skinparam classAttributeIconSize 0

class Company
{
  -String designation
  +getTestStore()
}


class Test {
  -String nhsCode
  -String internalCode
  -Client client
  -TestType testType
  -List<ParameterCategory> parameterCategory
  -List<Parameter> parameter
  -Date registrationDate
}

class TestStore {
  +getValidatedTestsFromClient(client)
}

class ViewTestsGUIScene {
}

class ViewTestsGUISceneController {
  -loadData()
}

class ViewTestDetailsGUIScene {
}

class ViewTestDetailsGUISceneController {
  -loadData()
}

ViewTestsGUIScene ..> ViewTestsGUISceneController
ViewTestsGUISceneController ..> ViewTestDetailsGUIScene
ViewTestDetailsGUIScene ..> ViewTestDetailsGUISceneController
ViewTestsGUISceneController ..> Company
ViewTestDetailsGUISceneController ..> Company
Company "1" --> "1..*" TestStore : has
TestStore "1" --> "*" Test : conducts
@enduml