@startuml
autonumber
actor "Client" as CLT

activate CLT
CLT -> ":System" : View tests. 
activate ":System"
":System" --> CLT : shows list of validated tests.
deactivate ":System"

CLT -> ":System" : selects test.
activate ":System"
":System" --> CLT : shows the details of the selected test (results and report).
deactivate ":System"

deactivate CLT
@enduml