@startuml
skinparam classAttributeIconSize 0

class Company
{
  -String designation
  +setCLA()
  +getTestStore()
  +getNextBarcode()
}

class ClinicalAnalysisLaboratory {
  -String name
  -String adress
  -long phoneNumber
  -long tin
  -TestStore testStore
  +getTestStore()
}

class Test {
  -String nhsCode
  -String internalCode
  -Client client
  -TestType testType
  -List<ParameterCategory> parameterCategory
  -List<Parameter> parameter
  -Date registrationDate
}

class Sample {
  -String barcode
  +Sample(barcode)
}

class TestStore {
  +getTestsWithoutSamples()
  +getTestByInternalCode(testCode)
  +createSample(barcode)
  +saveSample(t, s)
  -validateSample(s)
  -addSample(t, s)
}

class BarcodeController {
  +generateBarcode(barcode)
}

class API {
  +createUPCA(barcode)
  +setPrefferedBarHeight(height)
  +savePNG(bc,file)
}

class GenerateSampleUI {
}

class GenerateSampleController {
  +getTestsWithoutSamples()
  +createSamples(testCode, numberOfSamples)
}

GenerateSampleUI ..> GenerateSampleController
GenerateSampleController ..> Company
GenerateSampleController ..> BarcodeController
Company "1" --> "1..*" ClinicalAnalysisLaboratory : has
ClinicalAnalysisLaboratory "1" --> "1" TestStore : has
TestStore "1" --> "*" Test : conducts
Test "1" --> "*" Sample : requires
BarcodeController "1" --> "1" API : uses
@enduml