@startuml
autonumber
actor "Client" as CLT

activate CLT
CLT> ":System" : updating personal data. 
activate ":System"
":System" --> CLT: shows the clients data and let the client change it.
deactivate ":System"

CLT-> ":System" : write the new data.
activate ":System"
":System" --> CLT: changes the data and informs of the operation success.
deactivate ":System"

deactivate MEDLT
@enduml