@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

class Company {
  -designation
}

class Client {  
  -name
  -address
  -phoneNumber
  -eMail
  -sex
  -cnn
  -nhsNumber
  -birthDate
  -tin
}

Company "1" -- "1..*" Client : has >
@enduml