@startuml
skinparam classAttributeIconSize 0
hide methods

class TestType {
  -String designation
  -String collectingMethod
}

class Company {
  -designation
}

class Test {
}

class Administrator {
}

Company "1" --> "*" TestType : conducts
Test "*" --> "1" TestType : is of
Company "1" --> "*" Test : performs
TestType "*" --> "1" Administrator : created by
@enduml