@startuml
autonumber
actor "Administrator" as ADMIN

activate ADMIN
ADMIN-> ":System" : starts new type of test 
activate ":System"
":System" --> ADMIN : resquest data (i.e., code, description, collectingMethod)
deactivate ":System"

ADMIN -> ":System" : types requested data
activate ":System"
loop until no more categories are selected
	":System" --> ADMIN : shows parameter category list and ask to select one
	deactivate ":System"

	ADMIN -> ":System" : selects the parameter category
	activate ":System"
end
":System" --> ADMIN : shows all data and request confirmation 
deactivate ":System"

ADMIN -> ":System" : confirms the data
activate ":System"
":System" --> ADMIN : informs operation success 
deactivate ":System"

deactivate ADMIN
@enduml