@startuml
autonumber
actor "Medical Lab Technician" as MEDLT

participant ":GenerateSampleUI" as UI
participant ":GenerateSampleController" as CTRL
participant ":Company" as CMP
participant "ts:\nTestStore" as TS
participant "s:\nSample" as S
participant "T:\nTest" as T
participant "lt:\nList<Test>" as LT

activate MEDLT
MEDLT -> UI : starts new sample
activate UI
UI -> CTRL : lt=getTestsRegistered()
activate CTRL
CTRL -> CMP : ts=getTestStore()
activate CMP	
deactivate CMP
CTRL -> TS : lt=getTestsRegistered()
activate TS
deactivate TS
deactivate CTRL
UI --> MEDLT : shows tests list and ask to select one
deactivate UI

MEDLT -> UI : selects a test
activate UI
UI --> MEDLT : request how many samples to create
deactivate UI

MEDLT -> UI : types the number of samples to create
activate UI
UI -> CTRL : createSamples(testCode, numberOfSamples)
activate CTRL
CTRL -> TS : getTestByCode(testCode)
loop until all samples are created
end
UI -> CTRL : createTestType(code, description, collectingMethod, parameterCategoryCodes)
activate CTRL
loop until get all parameter categories by code
        CTRL -> pcStore : pc=cs.getParameterCategoryByCode(parameterCategoryCode)
        activate pcStore
        deactivate pcStore
end
CTRL -> CMP : ts=getTestTypeStore()
activate CMP
deactivate CMP
CTRL -> ttStore: tt=ts.createTestType(code, description, collectingMethod, parameterCategories)
activate ttStore
ttStore -> TET** : create(code, description, collectingMethod, parameterCategories)
deactivate ttStore
CTRL -> ttStore : validateTestType(tt)
activate ttStore
deactivate ttStore
CTRL -->  UI : result
deactivate ttStore
deactivate CMP
deactivate CTRL
UI --> MEDLT : shows all the data and request a confirmation
deactivate UI

MEDLT -> UI : confirms the data
activate UI
UI -> CTRL : saveTestType()
activate CTRL
CTRL -> ttStore : ts.saveTestType(tt)
activate ttStore
ttStore -> ttStore : validateTestType(tt)
ttStore -> ttStore : addTestType(tt)
UI --> MEDLT : informs operation success
deactivate ttStore
deactivate CTRL
deactivate UI

deactivate MEDLT
@enduml